# ═══════════════════════════════════════════════════════════════════
#  Hardware Configuration
# ═══════════════════════════════════════════════════════════════════
#  Boot loader, kernel, ZFS support, tmpfs root, swap, and tuning.
#
#  This file is intentionally hand-written (not generated by
#  nixos-generate-config) because the system uses an ephemeral
#  tmpfs root with disko-managed ZFS storage.
# ─────────────────────────────────────────────────────────────────
{ config, lib, ... }:

{
  # ─── Boot Loader ──────────────────────────────────────────────
  # systemd-boot on the ESP. ZFS is only on data partitions (not
  # root), so GRUB's ZFS support is unnecessary.
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # ─── Kernel ───────────────────────────────────────────────────
  boot.initrd.availableKernelModules = [
    "nvme" # NVMe SSD
    "xhci_pci" # USB 3.x
    "ahci" # SATA HDDs
    "usbhid" # USB keyboard/mouse
    "sd_mod" # SCSI disk
  ];
  boot.kernelModules = [
    "kvm-amd" # AMD virtualization
    "nct6775" # Nuvoton Super I/O (fan RPM + PWM control via hwmon)
  ];

  # ─── Hardware Monitoring ──────────────────────────────────────
  # The ASRock B650M Pro RS has a Nuvoton Super I/O chip (likely
  # NCT6799D, chip ID 0xd441) that is NOT on the nct6775 driver's
  # auto-detect whitelist. Force-loading exposes fan RPM readings
  # and PWM control via hwmon.
  #
  # The chip ID 0xd441 is confirmed on similar ASRock B650 boards
  # (B650E Steel Legend, B650E Taichi). If sensors-detect reports
  # a different ID on this board, update the force_id value.
  #
  # Verify after first boot:
  #   sudo sensors-detect   (look for "Found unknown chip with ID")
  #   dmesg | grep nct6775  (should show the chip being registered)
  #   sensors               (should show fan RPM and temp readings)
  boot.extraModprobeConfig = ''
    options nct6775 force_id=0xd441
  '';

  # ─── ZFS ──────────────────────────────────────────────────────
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.devNodes = "/dev/disk/by-id";

  # Required for ZFS — must be a unique 8-char hex string per host.
  networking.hostId = "163dd8b3";

  # ─── ZFS Maintenance ─────────────────────────────────────────
  services.zfs = {
    autoSnapshot = {
      enable = true;
      flags = "-k -p --utc";
      frequent = 0;
      hourly = 168;
      daily = 30;
      weekly = 0;
      monthly = 12;
    };
    autoScrub = {
      enable = true;
      interval = "monthly";
    };
    trim = {
      enable = true;
      interval = "weekly";
    };
  };

  # ─── ZFS ARC Tuning ──────────────────────────────────────────
  # Cap ARC at 16 GB (of 48 GB RAM). Leaves headroom for:
  #   ~4 GB  tmpfs root
  #   ~8 GB  zram swap (compressed)
  #   ~20 GB services + OS
  boot.kernelParams = [
    "zfs.zfs_arc_max=17179869184" # 16 GiB in bytes
  ];

  # ─── Ephemeral Root ───────────────────────────────────────────
  # Root is tmpfs — wiped every reboot. Only explicitly persisted
  # paths (via impermanence) survive. 4 GB is generous; typical
  # usage is 1-2 GB.
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "size=4G"
      "mode=755"
    ];
  };

  # ─── Critical Mount Flags ────────────────────────────────────
  # These must be available early in boot for impermanence bind
  # mounts and Nix store access. Disko creates the fileSystems
  # entries; we only add neededForBoot here.
  fileSystems."/persist".neededForBoot = true;
  fileSystems."/nix".neededForBoot = true;

  # ─── zram Swap ────────────────────────────────────────────────
  # Compressed in-RAM swap — primary swap device. Faster than SSD,
  # no disk wear. The 8 GB SSD swap partition (via disko) serves
  # as a secondary fallback for extreme memory pressure.
  zramSwap = {
    enable = true;
    memoryPercent = 16; # ~8 GB of 48 GB RAM
  };
}
